-- 코드를 작성해주세요
WITH ECOLI_PARENT AS (
    SELECT e1.ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA e1
    INNER JOIN ECOLI_DATA e2 ON e1.ID = e2.PARENT_ID
    GROUP BY ID
)

SELECT ed.ID, IFNULL(ep.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ed
LEFT JOIN ECOLI_PARENT ep ON ed.ID = ep.ID