-- 코드를 작성해주세요
WITH RANK_FISH AS (
    SELECT fi.ID, fni.FISH_NAME, 
        RANK() OVER (PARTITION BY fi.FISH_TYPE ORDER BY fi.LENGTH DESC) AS rnk, fi.LENGTH
    FROM FISH_INFO fi
    LEFT JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM RANK_FISH
WHERE rnk = 1
ORDER BY ID