-- GRADE가 존재하는 개발자
-- GRADE, ID, EMAIL
-- GRADE, ID 오름차순
SELECT CASE 
    WHEN ((SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') & SKILL_CODE AND (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') & SKILL_CODE) THEN 'A' 
    WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) THEN 'B' 
    WHEN ((SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') & SKILL_CODE) THEN 'C'
    END AS GRADE,
    ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID